import type { Merchant } from "./types";

export const MERCHANTS: Merchant[] = [
  {
    id: "jo-artbox",
    name: "ArtBox Amman",
    country: "JO",
    city: "Amman",
    categories: ["gift_shop", "custom_printing", "photo_studio", "handmade"],
    vibes: ["warm", "fun", "minimal", "modern"],
    budgets: ["low", "medium"],
    trusted: true,
    featured: true,
    website: "https://example.com/artbox-amman",
    instagram: "https://instagram.com/artbox.amman",
    phone: "+962790000001",
    whatsapp: "+962790000001",
    address: "Abdali, Amman",
    locationQuery: "ArtBox Amman Abdali",
  },
  {
    id: "jo-velvet-dining",
    name: "Velvet Table",
    country: "JO",
    city: "Amman",
    categories: ["restaurant", "fine_dining", "experience"],
    vibes: ["elegant", "luxury", "romantic", "warm"],
    budgets: ["medium", "high"],
    trusted: true,
    website: "https://example.com/velvet-table",
    instagram: "https://instagram.com/velvettable.jo",
    phone: "+962790000002",
    whatsapp: "+962790000002",
    address: "Sweifieh, Amman",
    locationQuery: "Velvet Table Sweifieh Amman",
  },
  {
    id: "jo-spark-tech",
    name: "Spark Tech",
    country: "JO",
    city: "Amman",
    categories: ["electronics"],
    vibes: ["modern", "fun", "minimal", "luxury"],
    budgets: ["low", "medium", "high"],
    trusted: true,
    website: "https://example.com/spark-tech",
    instagram: "https://instagram.com/sparktech.jo",
    phone: "+962790000003",
    whatsapp: "+962790000003",
    address: "Khalda, Amman",
    locationQuery: "Spark Tech Khalda Amman",
  },
  {
    id: "jo-calm-spa",
    name: "Calm House Spa",
    country: "JO",
    city: "Amman",
    categories: ["spa", "wellness"],
    vibes: ["warm", "luxury", "minimal"],
    budgets: ["medium", "high"],
    trusted: false,
    instagram: "https://instagram.com/calmhouse.spa",
    phone: "+962790000004",
    whatsapp: "+962790000004",
    address: "Dabouq, Amman",
    locationQuery: "Calm House Spa Dabouq Amman",
  },
  {
    id: "ae-desert-bloom",
    name: "Desert Bloom Gifts",
    country: "AE",
    city: "Dubai",
    categories: ["gift_shop", "flowers", "handmade", "custom_printing"],
    vibes: ["luxury", "elegant", "warm"],
    budgets: ["medium", "high"],
    trusted: true,
    website: "https://example.com/desert-bloom",
    instagram: "https://instagram.com/desertbloom.ae",
    phone: "+971500000001",
    whatsapp: "+971500000001",
    address: "Jumeirah, Dubai",
    locationQuery: "Desert Bloom Gifts Dubai",
  },
  {
    id: "ae-orbit-tech",
    name: "Orbit Gadgets",
    country: "AE",
    city: "Dubai",
    categories: ["electronics"],
    vibes: ["modern", "luxury", "fun"],
    budgets: ["medium", "high"],
    trusted: true,
    website: "https://example.com/orbit-gadgets",
    instagram: "https://instagram.com/orbitgadgets.ae",
    phone: "+971500000002",
    whatsapp: "+971500000002",
    address: "Dubai Marina, Dubai",
    locationQuery: "Orbit Gadgets Dubai Marina",
  },
  {
    id: "ae-luna-dining",
    name: "Luna Dining",
    country: "AE",
    city: "Dubai",
    categories: ["restaurant", "fine_dining"],
    vibes: ["romantic", "elegant", "luxury"],
    budgets: ["high"],
    trusted: true,
    website: "https://example.com/luna-dining",
    instagram: "https://instagram.com/lunadining.ae",
    phone: "+971500000003",
    whatsapp: "+971500000003",
    address: "Downtown Dubai",
    locationQuery: "Luna Dining Downtown Dubai",
  },
  {
    id: "sa-craftline",
    name: "CraftLine",
    country: "SA",
    city: "Riyadh",
    categories: ["handmade", "gift_shop", "home_decor"],
    vibes: ["warm", "minimal", "elegant"],
    budgets: ["low", "medium"],
    trusted: false,
    instagram: "https://instagram.com/craftline.sa",
    phone: "+966500000001",
    whatsapp: "+966500000001",
    address: "Olaya, Riyadh",
    locationQuery: "CraftLine Olaya Riyadh",
  },
];