// app/lib/merchantsSeed.ts
import type { Merchant } from "./merchantModel";

export const MERCHANTS: Merchant[] = [
  {
    id: "m1",
    name: { en: "Royal Fine Dining", ar: "مطعم رويال", fr: "Royal Fine Dining", tr: "Royal Fine Dining", es: "Royal Fine Dining" },
    country: "JO",
    city: "Amman",
    lat: 31.9539,
    lng: 35.9106,
    category: "fine_dining",
    priceTier: "high",
    qualityScore: 88,
    premiumScore: 80,
    reliabilityScore: 85,
    emotionAffinity: { love: 85, wow: 78, thanks: 60, surprise: 70 },
    tags: ["romantic", "vip"],
    links: [{ type: "maps", url: "https://maps.google.com" }],
  },
  {
    id: "m2",
    name: { en: "Zen Spa", ar: "زن سبا" },
    country: "JO",
    city: "Amman",
    lat: 31.965,
    lng: 35.915,
    category: "spa",
    priceTier: "mid",
    qualityScore: 82,
    premiumScore: 72,
    reliabilityScore: 84,
    emotionAffinity: { comfort: 90, love: 65, wow: 55, thanks: 60 },
    tags: ["relax", "premium"],
    links: [{ type: "maps", url: "https://maps.google.com" }],
  },
  {
    id: "m3",
    name: { en: "Signature Perfumes", ar: "عطور سيغنتشر" },
    country: "JO",
    city: "Amman",
    lat: 31.94,
    lng: 35.93,
    category: "perfume",
    priceTier: "mid",
    qualityScore: 78,
    premiumScore: 70,
    reliabilityScore: 80,
    emotionAffinity: { love: 75, wow: 70, thanks: 65, surprise: 72 },
    links: [{ type: "maps", url: "https://maps.google.com" }],
  },
  {
    id: "m4",
    name: { en: "Bloom Flowers", ar: "بلوم للزهور" },
    country: "JO",
    city: "Amman",
    lat: 31.98,
    lng: 35.89,
    category: "flowers",
    priceTier: "low",
    qualityScore: 74,
    premiumScore: 55,
    reliabilityScore: 78,
    emotionAffinity: { love: 80, apology: 70, thanks: 68, surprise: 60 },
    links: [{ type: "maps", url: "https://maps.google.com" }],
  },
  {
    id: "m5",
    name: { en: "Luxury Chocolates", ar: "شوكولاتة فاخرة" },
    country: "JO",
    city: "Amman",
    lat: 31.955,
    lng: 35.935,
    category: "chocolate",
    priceTier: "mid",
    qualityScore: 76,
    premiumScore: 62,
    reliabilityScore: 82,
    emotionAffinity: { thanks: 78, surprise: 74, love: 60, wow: 55 },
    links: [{ type: "maps", url: "https://maps.google.com" }],
  },
];