import { Merchant } from "./types";

export const MERCHANTS: Merchant[] = [
  {
    id: "m1",
    name: "Rose & Memory",
    country: "AE",
    worlds: ["emotional_gifts"],
    styles: ["romantic", "warm", "personal", "balanced"],
    budgets: ["low", "medium", "high"],
    urgencySupport: ["now", "today", "flexible"],
    scoreBoost: 2,
  },
  {
    id: "m2",
    name: "Royal Signature",
    country: "AE",
    worlds: ["luxury_items"],
    styles: ["formal", "elegant", "classic", "respectful"],
    budgets: ["medium", "high", "luxury"],
    urgencySupport: ["today", "this_week", "flexible"],
    scoreBoost: 3,
  },
  {
    id: "m3",
    name: "Blue Horizon Resort",
    country: "AE",
    worlds: ["experiences"],
    styles: ["romantic", "warm", "refined", "balanced"],
    budgets: ["high", "luxury"],
    urgencySupport: ["today", "this_week", "flexible"],
    scoreBoost: 5,
  },
  {
    id: "m4",
    name: "Tech Planet",
    country: "AE",
    worlds: ["electronics"],
    styles: ["fun", "playful", "friendly", "modern"],
    budgets: ["medium", "high"],
    urgencySupport: ["now", "today", "flexible"],
    scoreBoost: 1,
  },
  {
    id: "m5",
    name: "Sky Rush",
    country: "AE",
    worlds: ["adventure", "experiences"],
    styles: ["surprising", "playful", "fun"],
    budgets: ["high", "luxury"],
    urgencySupport: ["this_week", "flexible"],
    scoreBoost: 4,
  },
  {
    id: "jo1",
    name: "Hanadi Chocolate",
    country: "JO",
    worlds: ["emotional_gifts"],
    styles: ["warm", "elegant"],
    budgets: ["high"],
    urgencySupport: ["today", "this_week", "flexible"],
  },
  {
    id: "jo2",
    name: "Patchi Jordan",
    country: "JO",
    worlds: ["emotional_gifts", "luxury_items"],
    styles: ["elegant", "classic"],
    budgets: ["high", "luxury"],
    urgencySupport: ["today", "this_week", "flexible"],
  },
  {
    id: "jo3",
    name: "Flowers Jo",
    country: "JO",
    worlds: ["emotional_gifts"],
    styles: ["romantic", "warm"],
    budgets: ["medium", "high"],
    urgencySupport: ["today", "flexible"],
  },
  {
    id: "jo4",
    name: "Books@Cafe",
    country: "JO",
    worlds: ["experiences"],
    styles: ["friendly", "warm"],
    budgets: ["medium"],
    urgencySupport: ["today", "this_week", "flexible"],
  },
  {
    id: "jo5",
    name: "Fakhreldin Restaurant",
    country: "JO",
    worlds: ["experiences", "luxury_items"],
    styles: ["elegant", "formal"],
    budgets: ["high", "luxury"],
    urgencySupport: ["today", "this_week", "flexible"],
  },
  {
    id: "jo6",
    name: "Kempinski Ishtar Spa",
    country: "JO",
    worlds: ["experiences", "luxury_items"],
    styles: ["elegant", "romantic", "relaxing"],
    budgets: ["high", "luxury"],
    urgencySupport: ["this_week", "flexible"],
  },
  {
    id: "jo7",
    name: "Fairmont Amman Spa",
    country: "JO",
    worlds: ["experiences"],
    styles: ["elegant", "relaxing"],
    budgets: ["high", "luxury"],
    urgencySupport: ["this_week", "flexible"],
  },
  {
    id: "jo8",
    name: "Abu Shakra",
    country: "JO",
    worlds: ["experiences"],
    styles: ["friendly", "casual"],
    budgets: ["medium"],
    urgencySupport: ["today", "flexible"],
  },
  {
    id: "jo9",
    name: "Gift Corner",
    country: "JO",
    worlds: ["emotional_gifts", "luxury_items"],
    styles: ["friendly", "warm"],
    budgets: ["medium", "high"],
    urgencySupport: ["today", "flexible"],
  },
  {
    id: "jo10",
    name: "Porche Toys",
    country: "JO",
    worlds: ["kids_fun"],
    styles: ["fun", "playful"],
    budgets: ["medium"],
    urgencySupport: ["today", "flexible"],
  },
  {
    id: "uae_flowers",
    name: "Dubai Flowers Boutique",
    country: "AE",
    worlds: ["emotional_gifts"],
    styles: ["romantic", "warm"],
    budgets: ["medium", "high"],
    urgencySupport: ["today", "flexible"],
  },
  {
    id: "uae_choco",
    name: "Patchi UAE",
    country: "AE",
    worlds: ["emotional_gifts", "luxury_items"],
    styles: ["elegant", "classic", "warm"],
    budgets: ["high", "luxury"],
    urgencySupport: ["today", "this_week", "flexible"],
  },
  {
    id: "uae_spa",
    name: "Talise Spa",
    country: "AE",
    worlds: ["experiences", "luxury_items"],
    styles: ["elegant", "relaxing", "romantic"],
    budgets: ["high", "luxury"],
    urgencySupport: ["this_week", "flexible"],
  },
];